/* Autogenerated file (converted from TypeChain output). Do not edit manually. */
const { Migrations__factory } = require('./Migrations__factory')
const { SupplyChain__factory } = require('./SupplyChain__factory')

module.exports = { Migrations__factory, SupplyChain__factory }
