/* Autogenerated file (converted from TypeChain output). Do not edit manually. */
const factories = require('./factories')
const { Migrations__factory } = require('./factories/Migrations__factory')
const { SupplyChain__factory } = require('./factories/SupplyChain__factory')

module.exports = { factories, Migrations__factory, SupplyChain__factory }
